#ifndef DUMMY_MOTION_DATA_H
#define DUMMY_MOTION_DATA_H

// 더미 메시지들 (BLE 메시지 형식과 동일)
static const char* dummy_data[] = {
    "Activity:high Score:10.5",
    "Activity:high Score:0.5",
    "Activity:high Score:3.5",
    "Activity:high Score:10.5",
    "Activity:high Score:3",
    "Activity:high Score:4",
    "Activity:high Score:4",
    "Activity:high Score:2",
    "Activity:high Score:2.5",
    "Activity:high Score:10.5",
    "Activity:medium Score:10.7",
    "Activity:medium Score:10.7",
    "Activity:medium Score:22.7",
    "Activity:medium Score:30.5",
    "Activity:medium Score:42.7",
    "Activity:medium Score:12.7",
    "Activity:medium Score:42.7",
    "Activity:medium Score:2.7",
    "Activity:medium Score:2.7",
    "Activity:medium Score:12.7",
    "Activity:high Score:7.4",
    "Activity:high Score:7.4",
    "Activity:high Score:7.4",
    "Activity:high Score:627.4",
    "Activity:high Score:27.4",
    "Activity:high Score:30",
    "Activity:high Score:27.4",
    "Activity:high Score:60",
    "Activity:high Score:62",
    "Activity:high Score:7.4",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:low Score:2.1",
    "Activity:high Score:0.2",
    "Activity:high Score:0.2", 
    "Activity:high Score:70.2", 
    "Activity:high Score:0.2", 
    "Activity:high Score:0.2", 
    "Activity:high Score:0.2", 
    "Activity:high Score:30.2", 
    "Activity:high Score:3", 
    "Activity:high Score:25", 
    "Activity:high Score:7",  
    "Activity:high Score:40.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3",
    "Activity:high Score:0.3"
};

#define DUMMY_DATA_COUNT (sizeof(dummy_data) / sizeof(dummy_data[0]))

#endif // DUMMY_MOTION_DATA_H